title: Wes Bonelli
author: Wes Bonelli
email: wpbonelli@gmail.com

collections:
  publications:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "main"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  load_paths:
    - _sass
    - node_modules

exclude: []
