title: wes bonelli
author: wes bonelli
email: wpbonelli@gmail.com

collections:
  publications:
    output: true
  software:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "main"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  load_paths:
    - _sass
    - node_modules

exclude: []
