collections:
  publications:
    output: true

defaults:
  - scope:
      path: ""
      type: "publication"
    values:
      layout: "publication"
  - scope:
      path: ""
      type: "post"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
